// lib/main.dart
//
// WHAT CHANGED FROM PREVIOUS VERSION:
//   Removed: import supabase_flutter
//   Removed: final SupabaseClient supabase = Supabase.instance.client  (global var)
//   Removed: await Supabase.initialize(url: ..., anonKey: ...)
//   Added:   AuthService.listenForTokenRefresh() in initState (FCM token rotation)
//   Added:   authProvider.tryRestoreSession() in initState (persist login on restart)
//
// WHAT STAYS:
//   Firebase.initializeApp()         ← still needed (FCM only, not for auth)
//   FirebaseMessaging handlers       ← background + foreground notifications
//   FlutterLocalNotificationsPlugin  ← foreground notification display
//   All providers in MultiProvider   ← unchanged
//   MaterialApp + Consumer routing   ← unchanged
//
// Changes from previous version:
//   • Added _SplashScreen — shown while tryRestoreSession() runs on cold start
//   • _sessionChecked flag gates home routing until JWT restore completes
//   • StaffDashboardScreen now wired (was TODO comment)
//   • Theme improved: chipTheme + inputDecorationTheme set globally

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import 'package:flutter/material.dart';

import 'package:provider/provider.dart';
import 'package:slot_wise_booking/providers/admin_provider.dart';
import 'package:slot_wise_booking/providers/booking_provider.dart';
import 'package:slot_wise_booking/providers/notification_provider.dart';
import 'package:slot_wise_booking/providers/service_provider.dart';
import 'package:slot_wise_booking/providers/auth_provider.dart';
import 'package:slot_wise_booking/providers/slot_provider.dart';
import 'package:slot_wise_booking/providers/theme_provider.dart';

import 'package:slot_wise_booking/core/navigation/app_navigator.dart';
import 'package:slot_wise_booking/routes/routes.dart';
import 'package:slot_wise_booking/firebase_options.dart';

import 'package:slot_wise_booking/screens/nav/layout_nav.dart';
import 'package:slot_wise_booking/screens/admin/admin_dashboard_screen.dart';
import 'package:slot_wise_booking/screens/auth/login_screen.dart';
import 'package:slot_wise_booking/screens/splash_screen.dart';
import 'package:slot_wise_booking/screens/staff/staff_dashboard_screen.dart';

// ─────────────────────────────────────────────────────────────
// Background FCM handler — top-level function required by Firebase
// ─────────────────────────────────────────────────────────────
// Background message handler — MUST be a top-level function (not inside a class)
// Called when app is terminated or in background and a data message arrives
@pragma('vm:entry-point') // Required for release builds — prevents tree shaking
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // Ensure Firebase is initialized even when the app is in the background
  await Firebase.initializeApp();
  print('🔔 Background message: ${message.messageId}');
  // You can handle the message data here or show a local notification
  // Note: notification messages are auto-shown by the system in the background
}

// Global FlutterLocalNotificationsPlugin instance
// Used to display notifications when the app is in the foreground
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

// Android notification channel — must match channelId in notificationController.js
const AndroidNotificationChannel bookingChannel = AndroidNotificationChannel(
  'slotwise_bookings', // id — matches backend channelId
  'Booking Notifications', // name shown in Android settings
  description: 'Notifications for SlotWise booking updates',
  importance: Importance.high, // HIGH = shows as heads-up notification
  playSound: true,
);

void main() async {
  // required before any async work in main()

  WidgetsFlutterBinding.ensureInitialized();

  // Step 1: Initialize Firebase (needed for FCM — NOT for auth)
  // firebase_options.dart is generated by `flutterfire configure`
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Step 2: Register background message handler BEFORE any other Firebase calls
  // Must happen before runApp()
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  // Step 3: Create Android notification channel
  // Required for Android 8.0 (API 26+) — Without this, notifications on Android 8+ won't appear
  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin
      >()
      ?.createNotificationChannel(bookingChannel);

  // Step 4: Configure local notifications plugin
  const initializationSettingsAndroid = AndroidInitializationSettings(
    '@mipmap/ic_launcher',
  );
  const initializationSettingsIOS = DarwinInitializationSettings(
    requestAlertPermission: false, // We request manually below
    requestBadgePermission: false,
    requestSoundPermission: false,
  );
  const initializationSettings = InitializationSettings(
    android: initializationSettingsAndroid,
    iOS: initializationSettingsIOS,
  );

  await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse: (NotificationResponse response) {
      // Called when user taps a LOCAL notification
      // Use response.payload to navigate to the right screen
      print('🔔 Local notification tapped: ${response.payload}');
    },
  );

  // Step 5: Set foreground notification presentation options for iOS
  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: true,
    badge: true,
    sound: true,
  );

  // Step 3: launch app with providers
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => ServiceProvider()),
        ChangeNotifierProvider(create: (_) => SlotProvider()),
        ChangeNotifierProvider(create: (_) => BookingProvider()),
        ChangeNotifierProvider(create: (_) => NotificationProvider()),
        ChangeNotifierProvider(create: (_) => AdminProvider()),
      ],
      child: const SlotwiseApp(),
    ),
  );
}

// ─── Root widget ──────────────────────────────────────────────────────────────
class SlotwiseApp extends StatefulWidget {
  const SlotwiseApp({super.key});

  @override
  State<SlotwiseApp> createState() => _SlotwiseAppState();
}

class _SlotwiseAppState extends State<SlotwiseApp> {
  // false while tryRestoreSession() is running → shows SplashScreen
  bool _sessionChecked = false;

  @override
  void initState() {
    super.initState();
    _setupFirebaseMessaging();
    _restoreSession();
  }

  // Try to restore the previous session from secure storage
  // If a valid JWT exists, AuthProvider sets _user and routes to home screen
  // If not (expired or first launch), LoginScreen is shown
  // This runs after the first frame so Provider is available via context
  Future<void> _restoreSession() async {
    final auth = context.read<AuthProvider>();
    await auth.tryRestoreSession();

    // Apply role-default theme palette after session is known
    if (auth.user != null) {
      context.read<ThemeProvider>().applyRoleDefault(auth.user!.role);
      // Also pre-fetch notifications
      context.read<NotificationProvider>().fetchNotifications();
    }
 
    if (mounted) setState(() => _sessionChecked = true);
  
  }

  // Set up FCM foreground + tap handlers
  // Initialize notification listeners after the widget tree is built

  void _setupFirebaseMessaging() {
    // ── FOREGROUND messages ───────────────────────────────────────────────────
    // When app is open, FCM does NOT auto-show notification on Android
    // We use flutter_local_notifications to display it manually
    // FOREGROUND messages — app is open and visible
    // Without this listener, foreground FCM messages are silent on Android
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print('🔔 Foreground message: ${message.notification?.title}');

      final notification = message.notification;
      final android = message.notification?.android;

      if (notification != null && android != null) {
        // Show a local notification while the app is open
        flutterLocalNotificationsPlugin.show(
          notification.hashCode, // Unique ID per notification
          notification.title,
          notification.body,
          NotificationDetails(
            android: AndroidNotificationDetails(
              bookingChannel.id,
              bookingChannel.name,
              channelDescription: bookingChannel.description,
              icon: android.smallIcon,
              importance: Importance.high,
              priority: Priority.high,
            ),
          ),
          payload: message.data['type'], // Pass type for navigation
        );
      }
    });

    // BACKGROUND → FOREGROUND: User tapped notification to open the app
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('🔔 Notification opened app: ${message.data}');
      _handleNotificationTap(message.data);
    });
  }

  // Handle navigation based on the notification data payload
  void _handleNotificationTap(Map<String, dynamic> data) {
    final type = data['type'];
    final bookingId = data['booking_id'];

    switch (type) {
      case 'booking_confirmed':
      case 'booking_cancelled':
      case 'status_update':
        // Navigate to the bookings screen
        // Use your navigator key or router here
        print('Navigate to booking: $bookingId');
        AppNavigator.key.currentState?.pushNamed('/my-bookings');
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    // Read ThemeProvider — rebuilds when theme changes
    final tp = context.watch<ThemeProvider>();

    return MaterialApp(
      title: 'SlotWise',
      debugShowCheckedModeBanner: false,
      // ── Required for ApiService 401 handler ───────────────
      // Gives ApiService's interceptor access to Navigator and
      // ScaffoldMessenger without needing a BuildContext.
      navigatorKey: AppNavigator.key,

      // ── Theme wiring ─────────────────────────────────────
      theme:     tp.isDark ? null : tp.currentThemeData,
      darkTheme: tp.isDark ? tp.currentThemeData : null,
      themeMode: tp.themeMode,

      // ── Route handling ────────────────────────────────────
      // All routes are defined centrally in AppRouter.
      // Use AppRoutes.* constants + AppNav extension methods to navigate.
      onGenerateRoute: AppRouter.onGenerateRoute,
      initialRoute: AppRoutes.splash,
      
      // ── Home routing ──────────────────────────────────────
      // Splash while JWT restore runs → then role-based home
      home: !_sessionChecked
          ? const SplashScreen()
          : Consumer<AuthProvider>(
              builder: (_, auth, __) {
                if (!auth.isLoggedIn) return const LoginScreen();
                if (auth.isAdmin)     return const AdminDashboardScreen();
                if (auth.isStaff)     return const StaffDashboardScreen();
                return const CustomerShell();  // ← NEW: shell with PageView
              },
            ),
    );
  }
}
