// lib/main.dart
//
// WHAT CHANGED FROM PREVIOUS VERSION:
//   Removed: import supabase_flutter
//   Removed: final SupabaseClient supabase = Supabase.instance.client  (global var)
//   Removed: await Supabase.initialize(url: ..., anonKey: ...)
//   Added:   AuthService.listenForTokenRefresh() in initState (FCM token rotation)
//   Added:   authProvider.tryRestoreSession() in initState (persist login on restart)
//
// WHAT STAYS:
//   Firebase.initializeApp()         ← still needed (FCM only, not for auth)
//   FirebaseMessaging handlers       ← background + foreground notifications
//   FlutterLocalNotificationsPlugin  ← foreground notification display
//   All providers in MultiProvider   ← unchanged
//   MaterialApp + Consumer routing   ← unchanged

// import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:provider/provider.dart';
import 'package:slot_wise_booking/core/constants/app_colors.dart';
import 'package:slot_wise_booking/features/auth/providers/admin_provider.dart';
import 'package:slot_wise_booking/features/auth/providers/booking_provider.dart';
import 'package:slot_wise_booking/features/auth/providers/notification_provider.dart';
import 'package:slot_wise_booking/features/auth/providers/service_provider.dart';
import 'package:slot_wise_booking/features/auth/providers/auth_provider.dart';
import 'package:slot_wise_booking/features/auth/providers/slot_provider.dart';
import 'package:slot_wise_booking/features/auth/screens/admin_dashboard_screen.dart';
import 'package:slot_wise_booking/features/auth/screens/login_screen.dart';
import 'package:slot_wise_booking/features/auth/screens/service_screen.dart';
import 'package:slot_wise_booking/features/auth/screens/my_bookings_screen.dart';
import 'package:slot_wise_booking/firebase_options.dart';
// import 'package:supabase_flutter/supabase_flutter.dart';

// final SupabaseClient supabase = Supabase.instance.client;

// Background message handler — MUST be a top-level function (not inside a class)
// Called when app is terminated or in background and a data message arrives
@pragma('vm:entry-point')  // Required for release builds — prevents tree shaking
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
    // Ensure Firebase is initialized even when the app is in the background
    await Firebase.initializeApp();
    print('🔔 Background message: ${message.messageId}');
    // You can handle the message data here or show a local notification
    // Note: notification messages are auto-shown by the system in the background
}

// Global FlutterLocalNotificationsPlugin instance
// Used to display notifications when the app is in the foreground
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

// Android notification channel — must match channelId in notificationController.js
const AndroidNotificationChannel bookingChannel = AndroidNotificationChannel(
    'slotwise_bookings',          // id — matches backend channelId
    'Booking Notifications',      // name shown in Android settings
    description: 'Notifications for SlotWise booking updates',
    importance: Importance.high,  // HIGH = shows as heads-up notification
    playSound: true,
);


void main() async {
  // required before any async work in main()

  WidgetsFlutterBinding.ensureInitialized();

  // Step 1: Initialize Firebase (needed for FCM — NOT for auth)
  // firebase_options.dart is generated by `flutterfire configure`
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

    // Step 2: Register background message handler BEFORE any other Firebase calls
    // Must happen before runApp()
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

    // Step 3: Create Android notification channel
    // Required for Android 8.0 (API 26+) — Without this, notifications on Android 8+ won't appear
    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(bookingChannel);

    // Step 4: Configure local notifications plugin
    const initializationSettingsAndroid = AndroidInitializationSettings('@mipmap/ic_launcher');
    const initializationSettingsIOS = DarwinInitializationSettings(
        requestAlertPermission: false,  // We request manually below
        requestBadgePermission: false,
        requestSoundPermission: false,
    );
    const initializationSettings = InitializationSettings(
        android: initializationSettingsAndroid,
        iOS: initializationSettingsIOS,
    );

    await flutterLocalNotificationsPlugin.initialize(
        initializationSettings,
        onDidReceiveNotificationResponse: (NotificationResponse response) {
            // Called when user taps a LOCAL notification
            // Use response.payload to navigate to the right screen
            print('🔔 Local notification tapped: ${response.payload}');
        },
    );

    // Step 5: Set foreground notification presentation options for iOS
    await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
        alert: true,
        badge: true,
        sound: true,
    );

  // Step 2: initialise Supabase (replaces Firebase.initializeApp())

  // Get these values from: Supabase Console Settings API

  // await Supabase.initialize(
  //   url: 'https://vimzsdqpcteivojreifo.supabase.co',    // Project URL
  //   anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpbXpzZHFwY3RlaXZvanJlaWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NjUzNTcsImV4cCI6MjA4NzA0MTM1N30.I3PRf-e305Kwy7RDveFDEUPJyeuZds8_zhAwTnKGysw',// anon/public key
  // );

  // Step 3: launch app with providers
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => ServiceProvider()),
        ChangeNotifierProvider(create: (_) => SlotProvider()),
        ChangeNotifierProvider(create: (_) => BookingProvider()),
        ChangeNotifierProvider(create: (_) => NotificationProvider()),
        ChangeNotifierProvider(create: (_) => AdminProvider()),
      ],
      child: const SlotwiseApp()
    )
  );
}

// ─── Root widget ──────────────────────────────────────────────────────────────
class SlotwiseApp extends StatefulWidget {
  const SlotwiseApp({super.key});

  @override
  State<SlotwiseApp> createState() => _SlotwiseAppState();
}

class _SlotwiseAppState extends State<SlotwiseApp> {
  @override
    void initState() {
        super.initState();

        // Try to restore the previous session from secure storage
        // If a valid JWT exists, AuthProvider sets _user and routes to home screen
        // If not (expired or first launch), LoginScreen is shown
        // This runs after the first frame so Provider is available via context
        WidgetsBinding.instance.addPostFrameCallback((_) {
          context.read<AuthProvider>().tryRestoreSession();
        });

        // Set up FCM foreground + tap handlers
        // Initialize notification listeners after the widget tree is built
        _setupFirebaseMessaging();
    }

    void _setupFirebaseMessaging() {
        // ── FOREGROUND messages ───────────────────────────────────────────────────
        // When app is open, FCM does NOT auto-show notification on Android
        // We use flutter_local_notifications to display it manually
        // FOREGROUND messages — app is open and visible
        // Without this listener, foreground FCM messages are silent on Android
        FirebaseMessaging.onMessage.listen((RemoteMessage message) {
            print('🔔 Foreground message: ${message.notification?.title}');

            final notification = message.notification;
            final android = message.notification?.android;

            if (notification != null && android != null) {
                // Show a local notification while the app is open
                flutterLocalNotificationsPlugin.show(
                    notification.hashCode,  // Unique ID per notification
                    notification.title,
                    notification.body,
                    NotificationDetails(
                        android: AndroidNotificationDetails(
                            bookingChannel.id,
                            bookingChannel.name,
                            channelDescription: bookingChannel.description,
                            icon: android.smallIcon,
                            importance: Importance.high,
                            priority: Priority.high,
                        ),
                    ),
                    payload: message.data['type'],  // Pass type for navigation
                );
            }
        });

        // BACKGROUND → FOREGROUND: User tapped notification to open the app
        FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
            print('🔔 Notification opened app: ${message.data}');
            _handleNotificationTap(message.data);
        });
    }

    // Handle navigation based on the notification data payload
    void _handleNotificationTap(Map<String, dynamic> data) {
        final type = data['type'];
        final bookingId = data['booking_id'];

        switch (type) {
            case 'booking_confirmed':
            case 'booking_cancelled':
            case 'status_update':
                // Navigate to the bookings screen
                // Use your navigator key or router here
                print('Navigate to booking: $bookingId');
                break;
        }
    }


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SlotWise',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: AppColors.primary),
        appBarTheme: const AppBarTheme(
          backgroundColor: AppColors.primary,
          foregroundColor: Colors.white,
          elevation: 0,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: AppColors.primary,
            foregroundColor: Colors.white,
            minimumSize: const Size(double.infinity, 48),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
          ),
        ),
      ),
      // Decide initial screen based on auth state
      // Named routes are used in a few places (profile screen, notifications, etc.)
      // so register them here.  We keep home logic separate since initial screen
      // decision depends on auth state.
      routes: {
        '/my-bookings': (_) => const MyBookingsScreen(),
        // future named routes can go here
      },
      home: Consumer<AuthProvider>(
        builder: (context, authProvider, _) {
          if (!authProvider.isLoggedIn) return const LoginScreen();
          if (authProvider.isAdmin)     return const AdminDashboardScreen();
          return const ServicesScreen();
        },
      ),
    );
  }
}
